### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by jilv220** [jilv220/nos-ban#1]
- [x] kind 30000 - Categorized people
- [ ] kind 30078 - nosban-project-groupkey
- [ ] kind 4 => share-groupkey
- [ ] Encrypt all project contents with groupkey
